### ISSUE TITLE
Dealing with SVG sprite

### ISSUE THREAD

**Issue by iamvdo** [filamentgroup/svg-to-png#12]
How about dealing with SVG sprite, eg many icons in an unique file ?

For example, using `g` or `symbol` to get 3 png files:

``` svg
<svg xmlns="http://www.w3.org/2000/svg">
    <symbol id="icon1" viewBox="0 0 100 100">
        <path d="..." />
    </symbol>
    <symbol id="icon2" viewBox="0 0 50 50">
        <path d="..." />
    </symbol>
    <symbol id="icon3" viewBox="0 0 100 100">
        <path d="..." />
    </symbol>
</svg>
```

Is it realistic? Is it the purpose of this module ?

**Comment by jefflembeck** [comment]
@iamvdo as of right now, it's definitely not in scope, but it's a pretty cool idea that I'd entertain if somebody made a PR

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/filamentgroup/svg-to-png/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
