### ISSUE TITLE
Constrain size of pngs

### ISSUE THREAD

**Issue by jefflembeck** [filamentgroup/svg-to-png#5]
Right now we require SVGs to have width/height attrs. If we could allow them to have 100% attrs and still maintain a max size and keep the aspect ratio, that would be even better.

See: https://github.com/filamentgroup/grunticon/issues/23

**Comment by bonfish** [comment]
If I may: it would be perfect if the source SVGs don't have to have width and height set, and PNGs' size is calculated based on the `viewBox`. Constraining SVG with width and height is quite painful for responsive layouts.

**Comment by designorant** [comment]
/Apologies for a rather long background story on this turned out to be a 'must have' on the project I have been working on lately./

I have been working on a project with lots of SVGS and Grunticon along a polyfill to make `background-size: contain` work fine in IE8. Everything works kind of fine but the SVGs render very differently (and often rather badly) across various browsers with `width` and `height` specified in the SVGs. Either no attributes or 100% values do wonders with the results being almost 100% identical across a range of browsers. This is good.

However, 'responsive' SVGs break the PNG fallbacks as their custom/non-original size (be it 400x300 or anything I specify) creates extra whitespace that creates unexpected results in conjunction with `backgrond-size: contain`. In theory, being able to specify a custom size for each image would work here. That would be crazy laborious though.

I have looked into the source, and some related issues (https://github.com/filamentgroup/grunticon/issues/132, https://github.com/filamentgroup/grunticon/issues/53, https://github.com/filamentgroup/grunticon/issues/23, https://github.com/filamentgroup/grunticon/issues/10) and ended up here. Taking `viewBox` is really the visible width and height of a SVG, [I added a simple condition in `processor.js` that solved all the problems I have had](https://github.com/designorant/svg-to-png/compare/viewBox) with various other approaches:

````js
if (width === '100%' && height === '100%') {
    var viewbox = svgelem.getAttribute( 'viewBox' ).split(" ");
    width = viewbox[2] + 'px';
    height = viewbox[3] + 'px';
}
````

Naturally, this requires `width` and `height` to be set to `100%` but that was the quickest way to keep the `defaultWidth/defaultHeight` in place if anyone needs it. On a side note, is there a reason not to base `defaultWidth/defaultHeight` on the `viewBox`?

I see only one downside with this approach, albeit a good compromise as much as I understand SVGs and svg-to-png and Grunticon. In my case the `viewBox` is always equal to what `width` and `height` attributes say so if someone has a `width` and `height` much smaller than the `viewBox` the result would be much bigger than expected but even with that, those could be resized later on if needed. This is somewhat mentioned by @benfrain in https://github.com/filamentgroup/grunticon/issues/23.

**Comment by designorant** [comment]
I do not want to create a pull request until we discuss this but since this works well for me, here is a quick way of getting this up and running with Grunticon for anyone interested:

In your project, create `npm-shrinkwrap.json`:
````js
{
  "name": "foobar",
  "version": "0.0.0",
  "devDependencies": {
    "grunt-grunticon": {
      "version": "2.1.2",
      "from": "grunt-grunticon@~2.1.2",
      "dependencies": {
        "svg-to-png": {
          "version": "2.0.0",
          "from": "git://github.com/designorant/svg-to-png#viewBox"
        }
      }
    }
  }
}
````
Run `npm install`.

Remember that your SVG files need to explicitly specify `width="100%" height="100%"` for the PNGs to be rendered based on the `viewBox` values.

You may also want to read a bit about [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) just for the sake of it.

**Comment by jefflembeck** [comment]
@designorant I totally dig this, I need to test it pretty thoroughly though to make sure it works across the board like we'd like it to.

If you can create the PR, I'll move on from there.

Thanks!

**Comment by designorant** [comment]
The downside I have mentioned earlier is actually a big performance hit, particularly in conjunction with [background-size-polyfill](https://github.com/louisremi/background-size-polyfill) in IE8.

Until we have something like [`limit-png-width`](https://github.com/filamentgroup/grunticon/issues/23) the only workaround is to tweak the `viewBox` itself. This is a bit laborious but does the trick.

**Comment by designorant** [comment]
Furthermore, the above  `100%` workaround will not work with the default config of `svgmin` (`svgo`) plugin. You would need to disable the [`removeUnknownsAndDefaults` option](https://github.com/svg/svgo/blob/master/plugins/removeUnknownsAndDefaults.js) to leave the `100%` values intact.

**Comment by aish1550** [comment]
@jefflembeck @designorant Does anyone know if this has been merged or worked. Would be great to know if this works and could be merge to the master. Having a similar issue.

**Comment by aish1550** [comment]
@jefflembeck @designorant Sorry ignore me, just saw the other conversation
https://github.com/filamentgroup/svg-to-png/pull/10

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/filamentgroup/svg-to-png/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
