### ISSUE TITLE
Issues with file path and SVG count

### ISSUE THREAD

**Issue by milbz87** [filamentgroup/svg-to-png#6]
I have encountered an issue with svg-to-png (originally GruntIcon). The problem is that when i use svg-to-png with PhantomJS, the process crashes if i have a certain number of files in my SVG source folder (in the example below, this number is 42). The process also crashes if the location of the PNG folder is in a particular directory (in this case at least two directories deep). I have attached some zip files containing an example. please find the files at this location: 

https://drive.google.com/folderview?id=0BwXqK4syIILJQ0lMU2ZBc29RRG8&usp=sharing

Replication steps:

1.	Install node.js (obviously you'll already have this)
2.	Extract “SVG Files.zip” to C:\ but don’t create a new directory. You should end up with the path   “C:\aa\aa\aa\aa” which contains 42 svg files.
3.	Extract Test.zip to the directory C:\aa\aa\
4.	Open a command prompt.
5.	CD to C:\aa\aa\ (the location of gruntfile.js and package.json).
6.	Run “npm install”.
7.	Run “grunt”.

The PhantomJS process will hang as the C:\aa\aa\aa\aa folder contains 42 files. If you add a new file (43.png for example) or remove a file then the process is successful and all of the files are converted to PNG images in the target location.

If you move the location of "Test" up a directory (to C:\aa\Test) then the process will also work perfectly.

I've noticed that whenever PhantomJS crashes, only 19 files are copied to the PNG folder. This is a strange issue and thought i would raise it on here.

I hope the description and replication steps are clear.

Alex

**Comment by jefflembeck** [comment]
@milbz87 can you try this again with the newest version of svg-to-png?

**Comment by kenlyon** [comment]
I have re-tested it and can confirm svg-to-png 2.0.0 works. One side-effect I see is that the files are no longer output to the "svg" sub-directory, but I see that's because the pngfolder property has been dropped. No biggie. :)

I also ran the original test before changing the version number to 2.0.0 to make sure it was otherwise still a bug. It was. I just want to re-iterate, though, that if Gruntfile.js and package.json were in "C:\aa\aa\" the bug was NOT reproducible. They both had to be in "C:\aa\aa\aa\" for me to be able to reproduce it.

Thanks for the fix!
